### ISSUE TITLE
Failed to precompile Genie

### ISSUE THREAD

**Issue by imikim** [GenieFramework/Genie.jl#188]
**Describe the bug**
Just trying Genie for the first time. Cannot get the precompilation to work. First the error was in HttpCommon, which I then added and precompiled individually. After that another precompilation error: ERROR: could not load library "/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib"

**Error stacktrace**
julia> using Genie
[ Info: Precompiling Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e]
ERROR: could not load library "/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib"
dlopen(/Applications/Julia-1.3.app/Contents/Resources/julia/lib/julia/sys.dylib, 6): Symbol not found: _jl_apply_2va
  Referenced from: /Applications/Julia-1.0.app/Contents/Resources/julia/lib/julia/sys.dylib
  Expected in: /Applications/Julia-1.3.app/Contents/Resources/julia/bin/../lib/libjulia.dylib
 in /Applications/Julia-1.0.app/Contents/Resources/julia/lib/julia/sys.dylib
ERROR: LoadError: LoadError: IOError: write: broken pipe (EPIPE)
Stacktrace:
 [1] uv_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:953
 [2] unsafe_write(::Base.PipeEndpoint, ::Ptr{UInt8}, ::UInt64) at ./stream.jl:1007
 [3] macro expansion at ./gcutils.jl:91 [inlined]
 [4] write(::Base.PipeEndpoint, ::String) at ./strings/io.jl:186
 [5] create_expr_cache(::String, ::String, ::Array{Pair{Base.PkgId,UInt64},1}, ::Base.UUID) at ./loading.jl:1192
 [6] compilecache(::Base.PkgId, ::String) at ./loading.jl:1274
 [7] _require(::Base.PkgId) at ./loading.jl:1024
 [8] require(::Base.PkgId) at ./loading.jl:922
 [9] require(::Module, ::Symbol) at ./loading.jl:917
 [10] include at ./boot.jl:328 [inlined]
 [11] include_relative(::Module, ::String) at ./loading.jl:1105
 [12] include at ./Base.jl:31 [inlined]
 [13] include(::String) at /Users/imran/.julia/packages/Genie/UXDNm/src/Genie.jl:4
 [14] top-level scope at /Users/imran/.julia/packages/Genie/UXDNm/src/Genie.jl:38
 [15] include at ./boot.jl:328 [inlined]
 [16] include_relative(::Module, ::String) at ./loading.jl:1105
 [17] include(::Module, ::String) at ./Base.jl:31
 [18] top-level scope at none:2
 [19] eval at ./boot.jl:330 [inlined]
 [20] eval(::Expr) at ./client.jl:425
 [21] top-level scope at ./none:3
in expression starting at /Users/imran/.julia/packages/Genie/UXDNm/src/Flax.jl:7
in expression starting at /Users/imran/.julia/packages/Genie/UXDNm/src/Genie.jl:38
ERROR: Failed to precompile Genie [c43c736e-a2d1-11e8-161f-af95117fbd1e] to /Users/imran/.julia/compiled/v1.3/Genie/8eazC_8EDBq.ji.
Stacktrace:
 [1] compilecache(::Base.PkgId, ::String) at ./loading.jl:1283
 [2] _require(::Base.PkgId) at ./loading.jl:1024
 [3] require(::Base.PkgId) at ./loading.jl:922
 [4] require(::Module, ::Symbol) at ./loading.jl:917

**To reproduce**
(v1.3) pkg> st Genie
    Status `~/.julia/environments/v1.3/Project.toml`
  [c43c736e] Genie v0.22.8
  [cd3eb016] HTTP v0.8.8
  [77172c1b] HttpCommon v0.5.0
  [682c06a0] JSON v0.21.0
  [295af30f] Revise v2.5.0

**Additional context**
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.0.0)
  CPU: Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
Environment:
  JULIA_NUM_THREADS = 4

(v1.3) pkg> st
    Status `~/.julia/environments/v1.3/Project.toml`
  [c52e3926] Atom v0.11.1
  [336ed68f] CSV v0.5.20
  [5a033b19] CurveFit v0.3.2
  [a93c6f00] DataFrames v0.20.0
  [c43c736e] Genie v0.22.8
  [55e21f81] GoogleCloud v0.8.0
  [cd3eb016] HTTP v0.8.8
  [77172c1b] HttpCommon v0.5.0
  [682c06a0] JSON v0.21.0
  [e5e0dc1b] Juno v0.7.2
  [91a5bcdd] Plots v0.28.4
  [92933f4c] ProgressMeter v1.2.0
  [295af30f] Revise v2.5.0
  [88034a9c] StringDistances v0.5.2

**Comment by essenciary** [comment]
Doesn't look like a Genie issue - rather Julia/Pkg problem. Can you try installing in a new environment? 

Ex: 
```julia
$ mkdir genie_test
$ cd genie_test
$ julia
pkg> activate .
pkg> add Genie
julia> using Genie
```

**Comment by essenciary** [comment]
Closing this due to lack of feedback - please reopen if you want to add more info.
